-- ============================================================================
-- FarmTech Solutions - Fase 4
-- Modelagem do banco de dados (Oracle SQL Developer)
--
-- Modelo relacional simples (Cognitive Data Science):
--   CULTURA  1 ----< N  LEITURA_SENSOR
--
-- A tabela CULTURA guarda os parametros agronomicos de cada cultura e a
-- tabela LEITURA_SENSOR armazena cada leitura coletada pelos sensores IoT
-- (umidade, temperatura, pH, NPK) e os alvos calculados/previstos
-- (produtividade e volume de irrigacao).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Limpeza (permite reexecutar o script sem erro caso as tabelas ja existam)
-- ----------------------------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE LEITURA_SENSOR CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CULTURA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- ----------------------------------------------------------------------------
-- Tabela de dimensao: CULTURA
-- ----------------------------------------------------------------------------
CREATE TABLE CULTURA (
    id_cultura         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome               VARCHAR2(50) NOT NULL,
    ph_ideal_min       NUMBER(4,2),
    ph_ideal_max       NUMBER(4,2),
    umidade_ideal_min  NUMBER(5,2),
    umidade_ideal_max  NUMBER(5,2)
);

-- ----------------------------------------------------------------------------
-- Tabela de fato: LEITURA_SENSOR
-- ----------------------------------------------------------------------------
CREATE TABLE LEITURA_SENSOR (
    id_leitura          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cultura          NUMBER NOT NULL,
    datahora            TIMESTAMP DEFAULT SYSTIMESTAMP,
    umidade_solo        NUMBER(5,2),
    temperatura_ar      NUMBER(4,1),
    ph_solo             NUMBER(4,2),
    nitrogenio_n        NUMBER(5,2),
    fosforo_p           NUMBER(5,2),
    potassio_k          NUMBER(5,2),
    valor_ldr           NUMBER(6),
    produtividade_t_ha  NUMBER(6,2),
    volume_irrigacao_mm NUMBER(6,2),
    origem              VARCHAR2(10),
    CONSTRAINT fk_leitura_cultura
        FOREIGN KEY (id_cultura) REFERENCES CULTURA (id_cultura)
);

-- Indice para acelerar consultas por cultura/data
CREATE INDEX idx_leitura_cultura ON LEITURA_SENSOR (id_cultura, datahora);

-- ----------------------------------------------------------------------------
-- Carga inicial da dimensao CULTURA
-- ----------------------------------------------------------------------------
INSERT INTO CULTURA (nome, ph_ideal_min, ph_ideal_max, umidade_ideal_min, umidade_ideal_max)
VALUES ('Milho', 5.5, 6.8, 60, 85);

COMMIT;

-- Conferencia
SELECT * FROM CULTURA;
